site_name: Unlock-HF
site_author: moyanxinxu
site_description: Datawhale开源教程Unlock-HF
repo_url: https://github.com/datawhalechina/unlock-hf
edit_uri: edit/main/docs/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      use_pygments: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
nav:
  - Datasets工具: "chapter1/chapter1.md"
  - Transformers工具:
    - Pipeline工具:
      - Pipeline总览: 'chapter2/pipelines/pipelines.md'
    - Tokenizer工具: "chapter2/chapter2_2.md"
    - Model工具: "chapter2/chapter2_3.md"
  - PEFT工具:
    - PEFT总览: 'chapter3/peft_tour/peft_tour.md'
  - Diffusers工具:
    - DDPM数学原理: 'chapter5/ddpm/ddpm_math.md'
  - 代码案例:
    - 面对有害言论, 是时候让AI重拳出击了(多标签分类任务): "chapter6/multi-label-classification-of-toxic-comments/multi-label-classification-of-toxic-comments.md"
  - 附录:
    - 虚拟环境配置: "appendix/env_config/env.md"


plugins:
    - glightbox
    - search
    - git-revision-date-localized:
        enable_creation_date: true
    - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
          remove_comments: true
        cache_safe: true
    - mermaid2

theme:
  custom_dir: overides
  features:
    - content.code.copy
    - header.autohide
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - search.suggest
    - search.share
    - toc.integrate
    - content.action.edit
    - content.action.view
    - content.tabs.link
  icon:
    annotation: material/arrow-right-circle
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式