Package                                   Version
----------------------------------------- --------------
absl-py                                   2.1.0
accelerate                                1.0.1
aiofiles                                  23.2.1
aiohappyeyeballs                          2.4.3
aiohttp                                   3.10.10
aiosignal                                 1.3.1
albucore                                  0.0.17
albumentations                            1.4.18
annotated-types                           0.7.0
anyio                                     4.6.2.post1
argon2-cffi                               23.1.0
argon2-cffi-bindings                      21.2.0
arrow                                     1.3.0
asttokens                                 2.4.1
async-lru                                 2.0.4
async-timeout                             4.0.3
attrs                                     24.2.0
babel                                     2.16.0
beautifulsoup4                            4.12.3
bleach                                    6.1.0
certifi                                   2024.8.30
cffi                                      1.17.1
charset-normalizer                        3.4.0
click                                     8.1.7
colorama                                  0.4.6
comm                                      0.2.2
contourpy                                 1.3.0
csscompressor                             0.9.5
cycler                                    0.12.1
d2l                                       1.0.3
datasets                                  3.0.1
debugpy                                   1.8.7
decorator                                 5.1.1
defusedxml                                0.7.1
diffusers                                 0.30.3
dill                                      0.3.8
essentials                                1.1.5
essentials-openapi                        1.0.9
eval_type_backport                        0.2.0
evaluate                                  0.4.3
exceptiongroup                            1.2.2
executing                                 2.1.0
fastapi                                   0.115.2
fastjsonschema                            2.20.0
ffmpy                                     0.4.0
filelock                                  3.16.1
fonttools                                 4.54.1
fqdn                                      1.5.1
frozenlist                                1.4.1
fsspec                                    2024.6.1
ghp-import                                2.1.0
gitdb                                     4.0.11
GitPython                                 3.1.43
gradio                                    4.44.1
gradio_client                             1.3.0
grpcio                                    1.67.0
h11                                       0.14.0
htmlmin2                                  0.1.13
httpcore                                  1.0.6
httpx                                     0.27.2
huggingface-hub                           0.25.2
idna                                      3.10
imageio                                   2.36.0
importlib_metadata                        8.5.0
importlib_resources                       6.4.5
ipykernel                                 6.29.5
ipython                                   8.18.1
ipywidgets                                8.1.5
isoduration                               20.11.0
jedi                                      0.19.1
jieba                                     0.42.1
Jinja2                                    3.1.4
jsmin                                     3.0.1
json5                                     0.9.25
jsonpointer                               3.0.0
jsonschema                                4.23.0
jsonschema-specifications                 2024.10.1
jupyter                                   1.0.0
jupyter_client                            8.6.3
jupyter-console                           6.6.3
jupyter_core                              5.7.2
jupyter-events                            0.10.0
jupyter-lsp                               2.2.5
jupyter_server                            2.14.2
jupyter_server_terminals                  0.5.3
jupyterlab                                4.2.5
jupyterlab_pygments                       0.3.0
jupyterlab_server                         2.27.3
jupyterlab_widgets                        3.0.13
kiwisolver                                1.4.7
lazy_loader                               0.4
lxml                                      5.3.0
Markdown                                  3.7
markdown-it-py                            3.0.0
MarkupSafe                                2.1.5
matplotlib                                3.7.2
matplotlib-inline                         0.1.6
mdurl                                     0.1.2
mergedeep                                 1.3.4
mistune                                   3.0.2
mkdocs                                    1.6.1
mkdocs-get-deps                           0.2.0
mkdocs-git-revision-date-localized-plugin 1.2.9
mkdocs-glightbox                          0.4.0
mkdocs-link-marker                        0.1.3
mkdocs-link-preview-plugin                0.4.1
mkdocs-material                           9.5.41
mkdocs-material-extensions                1.3.1
mkdocs-minify-plugin                      0.8.0
mkdocs-print-site-plugin                  2.6.0
mpmath                                    1.3.0
multidict                                 6.1.0
multiprocess                              0.70.16
nbclient                                  0.10.0
nbconvert                                 7.16.4
nbformat                                  5.10.4
neoteroi-mkdocs                           1.1.0
nest-asyncio                              1.6.0
networkx                                  3.2.1
notebook                                  7.2.2
notebook_shim                             0.2.4
numpy                                     1.23.5
opencv-python-headless                    4.10.0.84
orjson                                    3.10.7
overrides                                 7.7.0
packaging                                 24.1
paginate                                  0.5.7
pandas                                    2.0.3
pandocfilters                             1.5.1
parso                                     0.8.4
pathspec                                  0.12.1
peft                                      0.13.2
pexpect                                   4.9.0
pillow                                    10.4.0
pip                                       24.2
platformdirs                              4.3.6
portalocker                               2.10.1
prometheus_client                         0.21.0
prompt_toolkit                            3.0.48
propcache                                 0.2.0
protobuf                                  5.28.2
psutil                                    6.0.0
ptyprocess                                0.7.0
pure_eval                                 0.2.3
pyarrow                                   17.0.0
pycparser                                 2.22
pydantic                                  2.9.2
pydantic_core                             2.23.4
pydub                                     0.25.1
Pygments                                  2.18.0
pymdown-extensions                        10.11.2
pyparsing                                 3.0.9
python-dateutil                           2.9.0.post0
python-json-logger                        2.0.7
python-multipart                          0.0.12
pytz                                      2024.2
PyYAML                                    6.0.2
pyyaml_env_tag                            0.1
pyzmq                                     26.2.0
qtconsole                                 5.6.0
QtPy                                      2.4.1
referencing                               0.35.1
regex                                     2024.9.11
requests                                  2.31.0
rfc3339-validator                         0.1.4
rfc3986-validator                         0.1.1
rich                                      13.9.2
rpds-py                                   0.20.0
ruff                                      0.6.9
sacrebleu                                 2.4.3
safetensors                               0.4.5
scikit-image                              0.24.0
scipy                                     1.10.1
semantic-version                          2.10.0
Send2Trash                                1.8.3
sentencepiece                             0.2.0
setuptools                                75.1.0
shellingham                               1.5.4
six                                       1.16.0
smmap                                     5.0.1
sniffio                                   1.3.1
soupsieve                                 2.6
stack-data                                0.6.3
starlette                                 0.40.0
sympy                                     1.13.1
tabulate                                  0.9.0
tensorboard                               2.18.0
tensorboard-data-server                   0.7.2
tensorboardX                              2.6.2.2
terminado                                 0.18.1
tifffile                                  2024.8.30
timm                                      1.0.11
tinycss2                                  1.3.0
tokenizers                                0.20.1
tomli                                     2.0.2
tomlkit                                   0.12.0
torch                                     2.5.0
torchvision                               0.20.0
tornado                                   6.4.1
tqdm                                      4.66.5
traitlets                                 5.14.3
transformers                              4.45.2
typer                                     0.12.5
types-python-dateutil                     2.9.0.20241003
typing_extensions                         4.12.2
tzdata                                    2024.2
uri-template                              1.3.0
urllib3                                   2.2.3
uvicorn                                   0.32.0
watchdog                                  5.0.3
wcwidth                                   0.2.13
webcolors                                 24.8.0
webencodings                              0.5.1
websocket-client                          1.8.0
websockets                                12.0
Werkzeug                                  3.0.4
wheel                                     0.44.0
widgetsnbextension                        4.0.13
xxhash                                    3.5.0
yarl                                      1.15.3
zipp                                      3.20.2
